version: "3"
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - api
      - client
    ports:
      - "3050:80"
  api:
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DATABASE_URL=${DATABASE_URL}
      - DB=${DB}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWTSECRET=${JWTSECRET}
      - NODE_ENV=${NODE_ENV}
      - RDS_DB_NAME=${RDS_DB_NAME}
      - RDS_HOSTNAME=${RDS_HOSTNAME}
      - RDS_PASSWORD=${RDS_PASSWORD}
      - RDS_PORT=${RDS_PORT}
      - RDS_USERNAME=${RDS_USERNAME}
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./api:/app
    depends_on:
      - "db"
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_CLOUDINARYCLOUD=${REACT_APP_CLOUDINARYCLOUD}
      - REACT_APP_CLOUDINARYPRESET=${REACT_APP_CLOUDINARYPRESET}
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app
    links:
      - api
    depends_on:
      - "api"

  db:
    image: postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
