version: "3"
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
        - api
        - client
    ports:
      - '3050:80'
  api:
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB=${DB}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWTSECRET=${JWTSECRET}
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./api:/app
    depends_on:
      - "db"
  client:
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_CLOUDINARYCLOUD=${REACT_APP_CLOUDINARYCLOUD}
      - REACT_APP_CLOUDINARYPRESET=${REACT_APP_CLOUDINARYPRESET}
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app
    links:
      - api
    depends_on:
      - "api"

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
