version: '3'
services:
    api:
      restart: always
      environment:
        - CHOKIDAR_USEPOLLING=true
      build: 
        context: .
        dockerfile: Dockerfile.dev
      ports:
        - "5000:5000"
      volumes:
        - /app/node_modules
        - .:/app

