version: '3'
services:
    api:
      restart: always
      environment:
        - CHOKIDAR_USEPOLLING=true
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_USER=${DB}
        - DB=${postgres}
        - DB_PASSWORD=${DB_PASSWORD}
        - JWTSECRET=${JWTSECRET}
      build: 
        context: .
        dockerfile: Dockerfile.dev
      ports:
        - "5000:5000"
      volumes:
        - /app/node_modules
        - .:/app
      depends_on:
        - "db"
      

    db:
      image: postgres 
      environment: 
          - POSTGRES_PASSWORD=${DB_PASSWORD}
      ports:
        - "5432:5432"