version: '3'
services:
    api:
      restart: always
      environment:
        - CHOKIDAR_USEPOLLING=true

      build: 
        context: .
        dockerfile: Dockerfile.dev
      ports:
        - "5000:5000"
      volumes:
        - /app/node_modules
        - .:/app
      depends_on:
        - "db"
      

    db:
      image: postgres 
      environment: 
          POSTGRES_PASSWORD: DB_PASS
          POSTGRES_USER: DB_USER
          POSTGRES_DB: DB
      ports:
        - "5432:5432"

